// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"mocku/backend/ent/careers"
	"mocku/backend/ent/note"
	"mocku/backend/ent/payment"
	"mocku/backend/ent/student"
	"mocku/backend/ent/users"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StudentCreate is the builder for creating a Student entity.
type StudentCreate struct {
	config
	mutation *StudentMutation
	hooks    []Hook
}

// SetIdentityCard sets the "identity_card" field.
func (sc *StudentCreate) SetIdentityCard(s string) *StudentCreate {
	sc.mutation.SetIdentityCard(s)
	return sc
}

// SetBirthDate sets the "birth_date" field.
func (sc *StudentCreate) SetBirthDate(t time.Time) *StudentCreate {
	sc.mutation.SetBirthDate(t)
	return sc
}

// SetPhone sets the "phone" field.
func (sc *StudentCreate) SetPhone(s string) *StudentCreate {
	sc.mutation.SetPhone(s)
	return sc
}

// SetAddress sets the "address" field.
func (sc *StudentCreate) SetAddress(s string) *StudentCreate {
	sc.mutation.SetAddress(s)
	return sc
}

// SetDistrict sets the "district" field.
func (sc *StudentCreate) SetDistrict(s string) *StudentCreate {
	sc.mutation.SetDistrict(s)
	return sc
}

// SetCity sets the "city" field.
func (sc *StudentCreate) SetCity(s string) *StudentCreate {
	sc.mutation.SetCity(s)
	return sc
}

// SetPostalCode sets the "postal_code" field.
func (sc *StudentCreate) SetPostalCode(i int) *StudentCreate {
	sc.mutation.SetPostalCode(i)
	return sc
}

// SetCreditUnitsAccumulated sets the "credit_units_accumulated" field.
func (sc *StudentCreate) SetCreditUnitsAccumulated(i int) *StudentCreate {
	sc.mutation.SetCreditUnitsAccumulated(i)
	return sc
}

// SetTotalAverage sets the "total_average" field.
func (sc *StudentCreate) SetTotalAverage(f float64) *StudentCreate {
	sc.mutation.SetTotalAverage(f)
	return sc
}

// SetSemester sets the "semester" field.
func (sc *StudentCreate) SetSemester(i int) *StudentCreate {
	sc.mutation.SetSemester(i)
	return sc
}

// SetUserID sets the "user" edge to the Users entity by ID.
func (sc *StudentCreate) SetUserID(id int) *StudentCreate {
	sc.mutation.SetUserID(id)
	return sc
}

// SetNillableUserID sets the "user" edge to the Users entity by ID if the given value is not nil.
func (sc *StudentCreate) SetNillableUserID(id *int) *StudentCreate {
	if id != nil {
		sc = sc.SetUserID(*id)
	}
	return sc
}

// SetUser sets the "user" edge to the Users entity.
func (sc *StudentCreate) SetUser(u *Users) *StudentCreate {
	return sc.SetUserID(u.ID)
}

// AddNoteIDs adds the "notes" edge to the Note entity by IDs.
func (sc *StudentCreate) AddNoteIDs(ids ...int) *StudentCreate {
	sc.mutation.AddNoteIDs(ids...)
	return sc
}

// AddNotes adds the "notes" edges to the Note entity.
func (sc *StudentCreate) AddNotes(n ...*Note) *StudentCreate {
	ids := make([]int, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return sc.AddNoteIDs(ids...)
}

// AddPaymentIDs adds the "payments" edge to the Payment entity by IDs.
func (sc *StudentCreate) AddPaymentIDs(ids ...int) *StudentCreate {
	sc.mutation.AddPaymentIDs(ids...)
	return sc
}

// AddPayments adds the "payments" edges to the Payment entity.
func (sc *StudentCreate) AddPayments(p ...*Payment) *StudentCreate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return sc.AddPaymentIDs(ids...)
}

// SetCareerID sets the "career" edge to the Careers entity by ID.
func (sc *StudentCreate) SetCareerID(id int) *StudentCreate {
	sc.mutation.SetCareerID(id)
	return sc
}

// SetNillableCareerID sets the "career" edge to the Careers entity by ID if the given value is not nil.
func (sc *StudentCreate) SetNillableCareerID(id *int) *StudentCreate {
	if id != nil {
		sc = sc.SetCareerID(*id)
	}
	return sc
}

// SetCareer sets the "career" edge to the Careers entity.
func (sc *StudentCreate) SetCareer(c *Careers) *StudentCreate {
	return sc.SetCareerID(c.ID)
}

// Mutation returns the StudentMutation object of the builder.
func (sc *StudentCreate) Mutation() *StudentMutation {
	return sc.mutation
}

// Save creates the Student in the database.
func (sc *StudentCreate) Save(ctx context.Context) (*Student, error) {
	return withHooks(ctx, sc.sqlSave, sc.mutation, sc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sc *StudentCreate) SaveX(ctx context.Context) *Student {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *StudentCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *StudentCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *StudentCreate) check() error {
	if _, ok := sc.mutation.IdentityCard(); !ok {
		return &ValidationError{Name: "identity_card", err: errors.New(`ent: missing required field "Student.identity_card"`)}
	}
	if v, ok := sc.mutation.IdentityCard(); ok {
		if err := student.IdentityCardValidator(v); err != nil {
			return &ValidationError{Name: "identity_card", err: fmt.Errorf(`ent: validator failed for field "Student.identity_card": %w`, err)}
		}
	}
	if _, ok := sc.mutation.BirthDate(); !ok {
		return &ValidationError{Name: "birth_date", err: errors.New(`ent: missing required field "Student.birth_date"`)}
	}
	if _, ok := sc.mutation.Phone(); !ok {
		return &ValidationError{Name: "phone", err: errors.New(`ent: missing required field "Student.phone"`)}
	}
	if v, ok := sc.mutation.Phone(); ok {
		if err := student.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "Student.phone": %w`, err)}
		}
	}
	if _, ok := sc.mutation.Address(); !ok {
		return &ValidationError{Name: "address", err: errors.New(`ent: missing required field "Student.address"`)}
	}
	if v, ok := sc.mutation.Address(); ok {
		if err := student.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "Student.address": %w`, err)}
		}
	}
	if _, ok := sc.mutation.District(); !ok {
		return &ValidationError{Name: "district", err: errors.New(`ent: missing required field "Student.district"`)}
	}
	if v, ok := sc.mutation.District(); ok {
		if err := student.DistrictValidator(v); err != nil {
			return &ValidationError{Name: "district", err: fmt.Errorf(`ent: validator failed for field "Student.district": %w`, err)}
		}
	}
	if _, ok := sc.mutation.City(); !ok {
		return &ValidationError{Name: "city", err: errors.New(`ent: missing required field "Student.city"`)}
	}
	if v, ok := sc.mutation.City(); ok {
		if err := student.CityValidator(v); err != nil {
			return &ValidationError{Name: "city", err: fmt.Errorf(`ent: validator failed for field "Student.city": %w`, err)}
		}
	}
	if _, ok := sc.mutation.PostalCode(); !ok {
		return &ValidationError{Name: "postal_code", err: errors.New(`ent: missing required field "Student.postal_code"`)}
	}
	if v, ok := sc.mutation.PostalCode(); ok {
		if err := student.PostalCodeValidator(v); err != nil {
			return &ValidationError{Name: "postal_code", err: fmt.Errorf(`ent: validator failed for field "Student.postal_code": %w`, err)}
		}
	}
	if _, ok := sc.mutation.CreditUnitsAccumulated(); !ok {
		return &ValidationError{Name: "credit_units_accumulated", err: errors.New(`ent: missing required field "Student.credit_units_accumulated"`)}
	}
	if v, ok := sc.mutation.CreditUnitsAccumulated(); ok {
		if err := student.CreditUnitsAccumulatedValidator(v); err != nil {
			return &ValidationError{Name: "credit_units_accumulated", err: fmt.Errorf(`ent: validator failed for field "Student.credit_units_accumulated": %w`, err)}
		}
	}
	if _, ok := sc.mutation.TotalAverage(); !ok {
		return &ValidationError{Name: "total_average", err: errors.New(`ent: missing required field "Student.total_average"`)}
	}
	if v, ok := sc.mutation.TotalAverage(); ok {
		if err := student.TotalAverageValidator(v); err != nil {
			return &ValidationError{Name: "total_average", err: fmt.Errorf(`ent: validator failed for field "Student.total_average": %w`, err)}
		}
	}
	if _, ok := sc.mutation.Semester(); !ok {
		return &ValidationError{Name: "semester", err: errors.New(`ent: missing required field "Student.semester"`)}
	}
	if v, ok := sc.mutation.Semester(); ok {
		if err := student.SemesterValidator(v); err != nil {
			return &ValidationError{Name: "semester", err: fmt.Errorf(`ent: validator failed for field "Student.semester": %w`, err)}
		}
	}
	return nil
}

func (sc *StudentCreate) sqlSave(ctx context.Context) (*Student, error) {
	if err := sc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	sc.mutation.id = &_node.ID
	sc.mutation.done = true
	return _node, nil
}

func (sc *StudentCreate) createSpec() (*Student, *sqlgraph.CreateSpec) {
	var (
		_node = &Student{config: sc.config}
		_spec = sqlgraph.NewCreateSpec(student.Table, sqlgraph.NewFieldSpec(student.FieldID, field.TypeInt))
	)
	if value, ok := sc.mutation.IdentityCard(); ok {
		_spec.SetField(student.FieldIdentityCard, field.TypeString, value)
		_node.IdentityCard = value
	}
	if value, ok := sc.mutation.BirthDate(); ok {
		_spec.SetField(student.FieldBirthDate, field.TypeTime, value)
		_node.BirthDate = value
	}
	if value, ok := sc.mutation.Phone(); ok {
		_spec.SetField(student.FieldPhone, field.TypeString, value)
		_node.Phone = value
	}
	if value, ok := sc.mutation.Address(); ok {
		_spec.SetField(student.FieldAddress, field.TypeString, value)
		_node.Address = value
	}
	if value, ok := sc.mutation.District(); ok {
		_spec.SetField(student.FieldDistrict, field.TypeString, value)
		_node.District = value
	}
	if value, ok := sc.mutation.City(); ok {
		_spec.SetField(student.FieldCity, field.TypeString, value)
		_node.City = value
	}
	if value, ok := sc.mutation.PostalCode(); ok {
		_spec.SetField(student.FieldPostalCode, field.TypeInt, value)
		_node.PostalCode = value
	}
	if value, ok := sc.mutation.CreditUnitsAccumulated(); ok {
		_spec.SetField(student.FieldCreditUnitsAccumulated, field.TypeInt, value)
		_node.CreditUnitsAccumulated = value
	}
	if value, ok := sc.mutation.TotalAverage(); ok {
		_spec.SetField(student.FieldTotalAverage, field.TypeFloat64, value)
		_node.TotalAverage = value
	}
	if value, ok := sc.mutation.Semester(); ok {
		_spec.SetField(student.FieldSemester, field.TypeInt, value)
		_node.Semester = value
	}
	if nodes := sc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   student.UserTable,
			Columns: []string{student.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(users.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.student_user = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sc.mutation.NotesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   student.NotesTable,
			Columns: []string{student.NotesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(note.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sc.mutation.PaymentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   student.PaymentsTable,
			Columns: []string{student.PaymentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sc.mutation.CareerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   student.CareerTable,
			Columns: []string{student.CareerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(careers.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.student_career = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// StudentCreateBulk is the builder for creating many Student entities in bulk.
type StudentCreateBulk struct {
	config
	err      error
	builders []*StudentCreate
}

// Save creates the Student entities in the database.
func (scb *StudentCreateBulk) Save(ctx context.Context) ([]*Student, error) {
	if scb.err != nil {
		return nil, scb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Student, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StudentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *StudentCreateBulk) SaveX(ctx context.Context) []*Student {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *StudentCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *StudentCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}
